services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambdalint_bandit
      region: eu-west-1
      role: arn:aws:iam::327092303989:role/lambda-lint_lambda_function
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAJTUSZCFJO2PNDFHQ
      secret_access_key:
        secure: "vm3QPkn0IIL7x8luhkpmDZAb5ro6k1igGUddcPzoMpkGC8oW/3Py346iQhCIdSk+ecmsWY/8mXguhlPB5/KdOrO+hrW3jZv2Coj+edvLnB5pAfLLYU86W0dwwCw8M334/daPzcLWwrXmMZJD/q+Gz+Y6ULc66Y94pDJZ64GdinF56B1DKTgasMwq4/CXYGbcd4CsQb0Mh5sq8MEIl580PTSfxN17XlroTe4BqkW10WcLmtAx1uOhbvo5hhA1MYCkMYPJUWLwoZR3oUTTDIPp8KfJkltq9I1m+h9Nh0siwvajemD67gSdBMVwTszptnX6uzczo2SKWZp8TsNjKmS98OJdEt0QL1nPAbl565xTYa7osy4QGofmXdFPBPxpoyLQP0zQspDZTLVxRDVhHhbP/vsKtTCBWLigpvO+Pppi4bCTK4mXW7icw3RpQN/n8CGaj++RhBby8nnQS09MBh2C/4R6/sNCkwDR8Itxq3Qld6JB9djylbCgpirfiNsCJf/CgRvYB3JKdcBiBqGtLNZIQgVHIqiYpcJu7qT4MDmByrvyMP1Tdl48nbV8m5A4Ojf/DV3Y9S2nLmEfpqzfQb2/p8xQJNLrxsWAGSnUtFqpdMuTfSOJF3bepOcNwAaKrHJ26DyXTH2XVmnWJIclj+u46p5ek2PwhPJIVVzltESZ38w="
      on:
        repo: FussyFox/bandit
