services:
- docker
sudo: true
language: python
python:
- '3.6'
jobs:
  include:
  - stage: deploy
    script: "./build_with_docker.sh"
    deploy:
      provider: lambda
      edge: true
      skip_cleanup: true
      function_name: lambda-lint_pycodestyle
      region: eu-west-1
      role: arn:aws:lambda:eu-west-1:327092303989:function:lambdalint_bandit
      runtime: python3.6
      module_name: main
      handler_name: handle
      timeout: 300
      dot_match: true
      access_key_id: AKIAIQHWJ4DO6Q4MCT2A
      secret_access_key:
        secure: XP9y6UnhF2WKnb6XRma+Kywwh5rCZeBYHSAVF0+b44tITtjS35JE6i5SJP0JOpp2R3uRw/CWI/WuNYmUP8tphduBx6UWBDWetmvWuA9XevQ+t7SnPvLFcPWAZKhU4osz58RYe+YzZFZZ7pvenR4tPOtVrj5pn7mmKEFTxvMuWIOrZGOK7teMkn6m7hpOnkh4jvucYnWHiU75N/XJQeUpdj3HF+Iuwc33M1U+HCH7fL9+Id0GaGQ3fNo//vDp3dctu4fz52ABsTgG6ltP3gIESzC/HcQ5I5muglStZeEvZma+c7BoU8Kh4HAYInF79bPdeol924QtXHimdViGPOH22ZuiV0mT+B+4EQ5w2Waj6cUJYtQabZYjrSIpy61EOGTBaScmN+xSZaPyj90Y6c57fltVgBVESvrtWreiDa1qRwlJ9RFypX9J3va2FPsdO+IHL9x/x+/wpOYyC4Q36ivmbv6p6g3KqXoYrtXqnhNyUG8F18LuH3jJw++McgWU4u9eIAgEr3TEOK2U5PDofOZ9Y+tl0W8z0lvtqrOI8QYQORIyoa2rd//ir8AH244RObt5xC8JVdJPmZkfO/bExzoPz9oDRaM/3jD/ewXxlwbzGwaWz3HF/l8SrqfKM+H1trL3a5bXXRtrAKR+O+PxFBbl1/f/XpIZQOY51W1dXeAuBfo=
      on:
        repo: LambdaLint/bandit
